---
version: "3.8"

services:
  swarm-gc:
    image: pschmitt/swarm-gc:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
    environment:
      - SLEEP_INTERVAL=43200
